"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

MydataFiles = [('resources', )]

APP = ['/Users/jharm/Desktop/Pyaera Final/src/Pyaera.py']
DATA_FILES = MydataFiles
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
